[theme]

# Primary accent for interactive elements
primaryColor = '#0e4529'

# Background color for the main content area
backgroundColor = '#cffae4'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#638071'

# Color used for almost all text
textColor = '#00000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"